### ISSUE TITLE
Better error if fastq files are not found

### ISSUE THREAD

**Issue by snacktavish** [McTavishLab/RapUp#14]
Output looks much cleaner!

In a trial run, I typo'd the suffix for my R2 reads, and got this error:
```
Individual Phycorder runs finished. Combining aligned query sequences and adding them to starting alignment
ls: cannot access '*_align.fas': No such file or directory
```

would be easier to catch if it reported directly, what fastq pairs were found, and errored if none were.

**Comment by snacktavish** [comment]
Actually - as part of this, a very first step checking that it can find and read all the input files (i.e. correct formats, correct path), before getting any further, and throwing a clear error and exiting would be helpful.

**Comment by jtfield** [comment]
The first message of
```
ls: cannot access '*_align.fas': No such file or directory
```
refers to files produced or not produced later in RapUp, generally to do with incorrect suffix setting. I'll add some checks at the beginning of the program to check assignments and inputs.

**Comment by jtfield** [comment]
Better error check added.
