### ISSUE TITLE
Comments on README

### ISSUE THREAD

**Issue by snacktavish** [McTavishLab/RapUp#17]
- README formatting needs cleanup
- needs install instructions, including dependencies, linked in README before the quickstart. Apt-get commands or wget commands, as well as  links will make it easier.

- errors like "Requires bcftools" etc. are helpful - but a link or apt-get would be more helpful.

The example doesn't run:
    ./multi_map.sh -a ./testdata/combo.fas -t ./testdata/combo.tre -d ./testdat

'Directory of read sequences can't be found. Check name and pathing.'

**Comment by snacktavish** [comment]
More README edits:

in "RapUp Controls and Flags For Use"
Separate out what flags are required vs optional.
- Is an input tree required?
- Are paired end reads split across two files required, or do merged files work?

Pull all gon_phyling info into a separate md, and link to it. Expectation is that most users will not need/use this section, as they already have a tree/alignment to update., right?

**Comment by jtfield** [comment]
Added clarification on which flags are required vs optional.

**Comment by jtfield** [comment]
README has been extensively updated.
Install instructions (particularly using Docker) have been added to the README. Alternative method install instructions have been added to another file (linked to by README).
multi_map.sh runs again.
Required flags and optional flags are indicated in help menu now.
Paired end reads are currently only in separate files but interleaved reads in single file will be added next version.
